### ISSUE TITLE
Tutorials for CI capturing failed states: Jenkins

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/docs#20]

**Comment by binocarlos** [comment]
fixing this to Jenkins for the moment

**Comment by deitch** [comment]
Didn’t I merge in a Jenkins tutorial last week?

**Comment by binocarlos** [comment]
@deitch this was me stealing the "gitlab" part of this issue so I could make another issue to go on the kanban :-) - I suppose yes this issue can be closed now! 👍

**Comment by deitch** [comment]
Ah got it. :-)
