### ISSUE TITLE
Docs content: architecture 

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/docs#22]
(with diagram, work with Pete), API, supported platforms: Kubernetes (GKE, OpenShift) & Docker (which versions?) installation & integration docs, which OSs?

**Comment by alice-sowerby** [comment]
@binocarlos reports this is done

**Comment by alice-sowerby** [comment]
Apologies, it was @alaric-datamesh that said it was done. Barring a diagram that is with @petercolesdc at https://github.com/dotmesh-io/brand-design/issues/20
