### ISSUE TITLE
Create diagram for concrete architecture page

### ISSUE THREAD

**Issue by alaric-datamesh** [dotmesh-io/docs#39]
I sketched a diagram of the concrete architecture:

[concrete-arch-diagram.zip](https://github.com/dotmesh-io/docs/files/1678546/concrete-arch-diagram.zip)

If somebody who's better at making things look nice than me makes a pretty version, I'll include it in the concrete architecture page!

**Comment by petercolesdc** [comment]
https://github.com/dotmesh-io/brand-design/issues/20 - closing
