### ISSUE TITLE
Searchbar styling

### ISSUE THREAD

**Issue by petercolesdc** [dotmesh-io/docs#42]
Algolia integration has borked styling a bit across all viewports (seems ok at mid range).

Also, search icon should no longer be a button, as it cannot submit anything

**Comment by petercolesdc** [comment]
Related. Search results are formatted poorly on mobile. It's too wide due to text not being stacked. I'm upping the importance of this one, as I'm not happy launching in this state. I'll try and fix the Z-index thing, but if you get to it before i do @danthebaker let me know

**Comment by petercolesdc** [comment]
@danthebaker I've done some CSS hackery in the aloglia settings, as I'm not sure how to go about doing it correctly. Nothing heavy handed, just a few width tweaks. I've also solved the Z-index issue.

However, this is untested outside of chrome right now, so I'm keeping issue open

**Comment by alice-sowerby** [comment]
I noticed that the search bar is in a non-standard place (LH menu) instead of top/top-right and dark rather than light as per most form fields/search bars. 

Don't know yet whether it would cause a problem, but one to watch out for when we do some testing on the docs with real users.

**Comment by petercolesdc** [comment]
@alice-sowerby I think it will be fine, as it's paired with the navigation and not off by itself on the left. I removed the little search icon as it doesn't submit the form (and users will almost certainly try that). This does have a downside, in that it feels less 'searchy'. Lets keep an eye on it.

**Comment by lukemarsden** [comment]
looks ok on mobile chrome on android to me now fwiw

**Comment by danthebaker** [comment]
Done
