### ISSUE TITLE
document how to make pull requests to change the docs

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/docs#46]
it would be great to encourage external contributors to fix docs bugs or contribute documentation.

document how to do that, by making pull requests into this repo.

while we're at it, we should probably document this repo's branching structure, which is:
> Branching structure for docs repo:
> commit all changes to master in advance of the 0.1 release
> (this is how kubernetes does it, and it works): when we do future feature (minor/major) releases of dotmesh (on the dotmesh repo's master, creating a release branch when we make the release), we should do the docs repo branching such that master is always what’s live on the docs site at the time, and docs that are going to go into a feature release get made on e.g. `release-0.2` and then merged into master when the release is made
> this makes it really easy to fix typos in the docs: just commit to master and CI will release them
docs that relate to only certain versions of the OSS releases: rather than complete copies of the docs site for different versions, we should mark features that only work in certain versions in situ e.g. “new in 1.8”
> if people really want to go and look at an old version of the docs, they can look at the git history

also formatting:
> Formatting docs markdown:
> Do not restrict docs to 80 character width on the screen.
> It makes diffs harder to read.
> Instead, put each sentence on its own line.

we should also clarify content (creative commons) and code (apache 2) licenses.

**Comment by danthebaker** [comment]
Not required.
