### ISSUE TITLE
links that include inline code need a combined link-code style

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/docs#49]
GitHub does a good job of this.

For example, [here is a link with some `code in it`](https://google.com).

And here is some `regular, unlinked code`.

At the moment, it's impossible to distinguish between linked and unlinked code in the docs.

Needs to look good in the [`only code is a link`](https://google.com) case and the [there is some `code` but also some normal text](https://google.com) cases.

**Comment by petercolesdc** [comment]
Fixed (could be better though, leaving open)
