### ISSUE TITLE
Collaboration tutorial

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/docs#56]

**Comment by lukemarsden** [comment]
still needs testing

**Comment by binocarlos** [comment]
I've gone through both the:

 * [library](https://docs.dotmesh.com/tutorials/library) and
 * [collaboration](https://docs.dotmesh.com/tutorials/collaboration/)

tutorials and updated the text and code so it works both locally and with a katacoda environment.

 * changed app so all traffic points to the web and it proxies to the users service so it works on katacoda
 * updated users service to log if environment is enabled and updated docs so the user doesn't need to change any code
 * some prompts to enter the dothub remote
 * some minor errors with syntax
