### ISSUE TITLE
spacing in the quick links

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/docs#58]
add a bit more spacing between items or some other distinguishing feature to make the quick links look like less of a wall of text

![screen shot 2018-02-06 at 10 58 10](https://user-images.githubusercontent.com/264658/35856039-b5f20eaa-0b2c-11e8-8d10-6585b1f214e4.png)

example from the collaboration tutorial

**Comment by petercolesdc** [comment]
Sure. It's a bit of a content wangle also, as ideally headers should be shorter (one of these is rather long). I'll add a tweak
