### ISSUE TITLE
update docs that 32607 is the new dotmesh port

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/docs#70]
Otherwise, next time we do a release the docs will be broken!

6969 -> 32607

**Comment by binocarlos** [comment]
This issue lead me to do a search of the docs which then reminded me that the firewall was only allowing 6969 - thank you to this issue +1 - have made: https://github.com/dotmesh-io/ops/issues/34 to handle this

**Comment by binocarlos** [comment]
I've updated all references from 6969 -> 32607.  I've not deployed to production yet although you can see it [on stage](https://stage.docs.dotmesh.com) - suggest we click deploy to production on [this pipeline](http://gitlab.dotmesh.io:9999/dotmesh/docs-sync/pipelines/3061) when we do the next release

**Comment by binocarlos** [comment]
Let's add the `release the staging version of docs` to the release process then we won't have tickets in blocked because of the release

**Comment by binocarlos** [comment]
This lives in dotmesh / `docs/release.md` - add these instructions to that file
