### ISSUE TITLE
upgrade instructions should mention gke, aks, etc variants

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/docs#73]
if someone has a GKE cluster, following the upgrading instructions at https://docs.dotmesh.com/install-setup/upgrading/#upgrading-dotmesh-on-kubernetes will make them sad because the cluster will be mysteriously broken - need to tell them to use the same yamels they used to install the cluster in the first place (e.g. https://docs.dotmesh.com/install-setup/gke/#dotmesh)

**Comment by prisamuel** [comment]
The YAML is different, but the same URL to do the installation.

**Comment by lukemarsden** [comment]
Fixed in http://gitlab.dotmesh.io:9999/dotmesh/docs-sync/commit/7d838399442d8c4fd0346ca6a6309f4e95161ada
