### ISSUE TITLE
Re-order steps to commit, checkout then open browser in hello-dotmesh-k8s tutorial

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/docs#76]
On the [hello-dotmesh-kubernetes](https://docs.dotmesh.com/tutorials/hello-dotmesh-kubernetes/#capture-the-empty-state) tutorial - we have the following order:

  * commit empty state
  * open browser
  * checkout branch

We should switch this to have:

  * commit empty state
  * checkout branch
  * open browser

Otherwise users are clicking around the browser before we have cloned the branch that should be empty.

**Comment by prisamuel** [comment]
This would be fixed with https://github.com/dotmesh-io/dotmesh/issues/159
