### ISSUE TITLE
README for Nvidia's container registry

### ISSUE THREAD

**Issue by satsumas** [dotmesh-io/docs#86]
Dotscience are hosting a container image in GTC's registry: https://ngc.nvidia.com

The image readme should give:

*  snappy intro to Dotscience 
* access to product sign-up page, to be closely monitored
* instructions to get up and running

[guidelines for README here](https://mail-attachment.googleusercontent.com/attachment/u/0/?ui=2&ik=17c6fbe313&attid=0.1&permmsgid=msg-f:1626690891196797245&th=16932abf3926113d&view=att&disp=inline&realattid=16932ab9ff595f8cb21&saddbat=ANGjdJ_Z13eQwXwT2ZFx55kakrfOOK-2G2mv3W6KUQNSRgkbFHPPWV_VNmWM0gL81DLOakGa5Y5k0ALLwASMSBKHqVUFbgiQUgTgVxPLcs9OGEY6zBd6_sQbrarDuON9zWtP6sFseSv2fFtnBwEHeh__VYN00_J4Yyolx7HWBbNTghQiC_5pWsujMaE_fjawgc9uc-2u_ipPAcbloGtq85Oka6xV0rvGPqChr3c_gvWGncYuIFaWVIrUaMo7c6L1t9uhjmA9vpc38JAGaL7k6rR2IRdDd0sJMlhvdI5g7xj3IEQkcvGWsYSY6WyqcEWWeg1VbcdnQYPukLpD0T9QvRkybc95p8MQh6t91pseWD5MPcH8FINgu5JekDoer_R3emm4I7-TD1f5QrKFmgXrzTRdvV1Y3nMKLpYuZPBiB7xS_Rd9CKFaXTLDLETQ5UUYmFU9RmII22D_STSJQ_G25tnfLDk1LKvJS5wMujWbCjk1XajN8UXfFfei0dm-RKzFa-eHSTXkd5cyE304ObgVgJR0j_bGRnxTCzDhsXN-ixQbZCPllyH9boRGyGFyqYWh5GeEkGsDOpRxGNfsyXfD0vZKiPdSP0-OXHmRTCsCfssI2VSWNYoFqcfbJYqrxoINgULwue6TdFK0iMTL-qoQuIZhH1Q6o3hmUibCMpWG2g)

**Comment by satsumas** [comment]
... needs updating with instructions on auth token for `docker login` to nvidia registry.

**Comment by satsumas** [comment]
https://github.com/dotmesh-io/registry-docs/blob/master/NCG_README.md

**Comment by alice-sowerby** [comment]
done
