### ISSUE TITLE
documentation improvements

### ISSUE THREAD

**Issue by eugenemi** [dotmesh-io/docs#88]
* https://docs.dotscience.com/ Concepts come first on the right list, but Set Up card comes up first in the cad view on the right.
* https://docs.dotscience.com/setup/set-up-aws-vm/ does not mention docker run --name dotscience-runner
* Broken link on https://docs.dotscience.com/setup/set-up-google-cloud-vm/ : https://docs.dotscience.com/setup/set-up-google-cloud-vm/attach-your-runner-to-dotscience 
* https://docs.dotscience.com/tasks/add-a-collaborator/ bullet point list is displayed as a single sentence
* https://docs.dotscience.com/glossary/ empty; remove
* https://docs.dotscience.com/references/ R is empty; remove
* A diagram including entities below would help me understand various components 
  * Hub
  * Cloud runner with docker container
  * My laptop with
      * docker container runner
      * ds cli outside docker container
      * Dotsciense web interface pointing at Jupiter interface (is it running on the associated runner?)
      * Jupiter interface can host a terminal, that can execute a python script with ds.publish().  What does ds.publish() do in this context?

**Comment by alice-sowerby** [comment]
Now rolled into this issue https://github.com/dotmesh-io/dotscience-docs/issues/7
